apiVersion: v1
kind: Service
metadata:
  name: perf-netcorebaseline
  namespace: perf
  labels:
    app: perf-netcorebaseline
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  selector:
    app: perf-netcorebaseline
  type: LoadBalancer
  ports:
  - name: http
    port: 5001
    targetPort: http
    protocol: TCP